spring:
  datasource:
    url: jdbc:tc:postgresql:15:///spotguard_test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

app:
  security:
    jwt:
      secret-key: test-secret-key-for-unit-tests-only-1234567890abcdef
      expiration-time: 86400000
